### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by Fil** [ipfs-shipyard/shared-editing-demo#1]
I watched the (very exciting) video, then followed the procedure in README. The app builds, the pages show an editable text, but they don't sync.

Here's what the console says in both pages:

<img width="499" alt="capture d ecran 2017-07-18 a 13 16 41" src="https://user-images.githubusercontent.com/7001/28314596-7b39816e-6bbb-11e7-8eda-a891e32fb81a.png">
<img width="498" alt="capture d ecran 2017-07-18 a 13 16 49" src="https://user-images.githubusercontent.com/7001/28314597-7b3d7864-6bbb-11e7-871b-4b5e0503d66f.png">

**Comment by daviddias** [comment]
Hi @Fil, thanks for the report!

It seems that the code had a race condition that now should be fixed. Mind trying latest master? I also published it to IPFS https://ipfs.io/ipfs/QmUS49q6Hr6r61aciF3wPJd1xivstjFnyUWbUnrYom8dHE/

**Comment by Fil** [comment]
looks fine now — thanks!
