### ISSUE TITLE
Fails if recompiled

### ISSUE THREAD

**Issue by mitra42** [ipfs-shipyard/shared-editing-demo#3]
The browserified version in the repository works (apart from the thread crash) BUT there appears to be some inconsistency with current packages.  It gives an error 
`utils.js:3 Uncaught Error: This command must be run in online mode. Try running 'ipfs daemon' first.
    at Object.401 (utils.js:3)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.394.../utils (swarm.js:8)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.383../bitswap (index.js:17)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.<anonymous> (index.js:16)`

**Comment by daviddias** [comment]
Fixed with https://github.com/ipfs-shipyard/shared-editing-demo/pull/5

@mitra42 please try with a fresh pull from master. Let me know if doesn't work (worked locally), will reopen if necessary.

**Comment by mitra42** [comment]
David - can you reopen this, or should I create a new bug report?

Anyway ... npm install  as usual gives pages of errors the first time through, nothing that looked significant, and a second run was clean. BUT build doesn't work.

This was on OSX, and after it failed the first time I deleted the entire directory (including node_modules) and re-cloned with same result ... See below. 
```

mitraglass:shared-editing-demo mitra$ npm run build

> ipfs-yjs-demo@0.0.1 build /Users/mitra/git/_github_ipfs-labs/shared-editing-demo
> browserify src/app.js -o public/js/app.js -d

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'public/js/app.js.tmp-browserify-68841457307646747310'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-yjs-demo@0.0.1 build: `browserify src/app.js -o public/js/app.js -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipfs-yjs-demo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mitra/.npm/_logs/2017-08-31T17_52_44_278Z-debug.log
```

**Comment by daviddias** [comment]
I was able to reproduce the issue that you are seeing, @mitra42. It seems that when I defaulted to have the built file generated locally and not committed to GitHub, the folder `public/js` got empty and so git doesn't check it to the repo. 

I've fixed this by adding a simple file to the folder, so that the folder is present when you git clone. Fix: https://github.com/ipfs-shipyard/shared-editing-demo/commit/af786f746548a5c159386815e19187cfce603028 try again with pulling from master :)

**Comment by mitra42** [comment]
COnfirmed - it compiles now, though as reported in #4 this version (both freshly compiled and as pushed to IPFS by you) doesn't do any sharing (not even between tabs on one browser) and crashed firefox as reported in #2 .

By the way - interested in your decision not to push the bundled version to the repo, I find the bundled version useful as a way to distinguish between compilation/node/npm issues and issues with the app itself.
