### ISSUE TITLE
Wont work between machines

### ISSUE THREAD

**Issue by mitra42** [ipfs-shipyard/shared-editing-demo#4]
Another problem with the shared-editing-demo that would be good to document if its the intention ... 

If you load it up  (current git repository version NOT the re-compiled version which doesnt work at all) it advertises both the 127.0.0.1:12345 address, but also a local network address e.g. 192.168.0.123:12345   If you try and reach that address from another machine it complains about "Could not read property "generate" of undefined (full stacktrace below). I think I saw a similar bug reported elsewhere that related to the server being HTTP rather than HTTP, but if it won't work on HTTP across a LAN then it might be good to document that :-)

**Comment by mitra42** [comment]
`utils.js:3 Uncaught Error: This command must be run in online mode. Try running 'ipfs daemon' first.
    at Object.401 (utils.js:3)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.394.../utils (swarm.js:8)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.383../bitswap (index.js:17)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.<anonymous> (index.js:16)`

**Comment by mitra42** [comment]
The stack trace is as follows (note i posted the wrong one earlier and deleted).

`Uncaught TypeError: Cannot read property 'generateKey' of undefined
    at Object.exports.generateKey (app.js:70748)
    at Object.generateKeyPair (app.js:71551)
    at Object.exports.generateKeyPair (app.js:71067)
    at waterfall (app.js:113096)
    at nextTask (app.js:29146)
    at exports.default (app.js:29156)
    at Function.exports.create (app.js:113095)
    at waterfall (app.js:129517)
    at nextTask (app.js:29146)
    at next (app.js:29153)`

**Comment by mitra42** [comment]
Note the other generateKey error reported this weekend by someone else was at https://github.com/ipfs/js-ipfs/issues/964#issuecomment-325259785

**Comment by daviddias** [comment]
It is supposed to work between machines and it will work if you load both of them through Localhost. It is a WebCrypto limitation, read more at:

- https://github.com/ipfs/js-ipfs/issues/964#issuecomment-325269476
- https://github.com/libp2p/js-libp2p-crypto/issues/105

**Comment by mitra42** [comment]
It won't work currently ... 
STR (on Mac). 
git clone https://github.com/ipfs-labs/shared-editing-demo.git. 
cd shared-editing-demo.git. 
npm install. 
DO NOT `run npm run compile` - it will create a version that fails with https://github.com/ipfs-shipyard/shared-editing-demo/issues/3. 
npm start. 
On Chrome (it fails in Firefox immediately). 
http://localhost:12345. 
It opens up a text editor - View/Developer/Javascript Console to see the errors. 
Same thing on second browser (on a different machine) 
Type on one browser (either)  
Notice in console on BOTH browsers:  
client.js:18 WebSocket connection to 'wss://sfo-1.bootstrap.libp2p.io/' failed: Error during WebSocket handshake: Unexpected response code: 502  

(Note if you now wait 5 minutes, both Chrome pages should crash with "Aw Snap" illustrating the bug in https://github.com/ipfs-shipyard/shared-editing-demo/issues/2

**Comment by daviddias** [comment]
I got it working. I've also published the latest to this hash https://ipfs.io/ipfs/QmUS49q6Hr6r61aciF3wPJd1xivstjFnyUWbUnrYom8dHE/ can you try it?

**Comment by mitra42** [comment]
Following that links seems to load ok, but no sharing happens (Not between browser tabs on Chrome; between Chrome & Firefox on same machine or back and forth with another machine.
Console logs don't show any problems except the WebSocket errors  reported on other Issues.

**Comment by daviddias** [comment]
@mitra42 I wonder if that is because of your Wifi set up and possible double NAT/Firewall. I've tested it on 2 computers and in two home network setups and worked fine. Just tested again, might try again?

**Comment by mitra42** [comment]
Possible ... but this was working before (on these machines to themselves), I'm seeing the same problem and both with the IPFS and localhost version. I'm seeing it to the bootstrap nodes and errors reported on sfo-1 and sfo-2. 
On Chrome  I'm also seeing:
websocket errors on star-signal.cloud.... 
complaints about emitter.setMaxListeners 
"underlying socket has been closed" errors. 

I'm just now (on same browser as had all those errors) starting to see some text from someone else popping up on the window - 
Can't test on Firefox as crashes browser (problem #2 ) usually within a minute.

**Comment by mitra42** [comment]
And now its working between those two machines (using the version on [IPFS](https://ipfs.io/ipfs/QmUS49q6Hr6r61aciF3wPJd1xivstjFnyUWbUnrYom8dHE/) and between that and the localhost version  ... no change in network here, so there is something intermittent going on. 

I suggest leaving this Issue open until can find out what the intermittency is that is causing it.

**Comment by daviddias** [comment]
The issue you saw there was me redeploying the star-signal :) all good here then!

**Comment by vasa-develop** [comment]
Just checked it out...it's working indeed on chrome
