### ISSUE TITLE
Circle is hanging for me

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/shared-editing-demo#6]
Need to try again later, right now _clicking start_ does nothing

https://circleci.com/setup-project/gh/ipfs-shipyard/shared-editing-demo

**Comment by daviddias** [comment]
@VictorBjelkholm this is the kind of issue I'm having with circle

**Comment by victorb** [comment]
@diasdavid hm, seems to be a permission thing. Could you make sure this repository has the same permissions in Github setup as the rest of the repos in ipfs-shipyard? I was able to activate CircleCI for ipfs-level for example (https://circleci.com/gh/ipfs-shipyard/ipfs-level/1) but not this repository...

**Comment by daviddias** [comment]
It's an org level permission so it should be the same:

![image](https://user-images.githubusercontent.com/1211152/29960664-7eba6a22-8ef4-11e7-94a8-3c0921b13c92.png)

**Comment by victorb** [comment]
From IRC:

```
10:14:04 <@victorbjelkholm> daviddias: for ipfs-shipyard/shared-editing-demo + circleci, I meant the github permissions for the users of the repository
10:14:10 <@victorbjelkholm> not the circleci application access
10:14:35 <@victorbjelkholm> I seem to have admin access to all repos but shared-editing-demo, so something tells me the permissions are different there
10:33:39 <@victorbjelkholm> daviddias: did a quick try with jenkins as well and somewhere the permissions are wonky as jenkins can't set commit status either
10:43:53 <@daviddias> victorbjelkholm: ah! just added it to the team shipyard-maintainers
```

And now it's working! 

https://circleci.com/gh/ipfs-shipyard/shared-editing-demo/1

🎉
